[package]
name = "rusty-socket"
version = "0.1.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
urlencoding = "2.1.3"
signal-hook = "0.3.17"
mime_guess = "2.0.5"
